# Generated by Django 5.0.2 on 2024-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_balance_balance_alter_balance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
