version: '3.8'

services:
  django:
    build:
      context: ./backend 
      dockerfile:  Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - psql  
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

  psql:
    image: postgres
    container_name: psql
    environment: 
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=pft,fkb19RU
      -  POSTGRES_DB=project_database
  
  redis:
    image: redis:latest
    container_name: redis
  
  celery:
    build:  ./backend
    command: celery -A myproject worker  --loglevel=info --beat
    volumes:
      - ./backend:/backend
    depends_on: 
      - psql
      - redis
    expose: 
      - "8001"
    environment: 
      - REDIS_HOST=redis
  
  react:
    build:
      context: ./frontend
      dockerfile:  Dockerfile
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm start"
    expose:
      - "3000"