# Generated by Django 5.0.3 on 2024-03-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_balance_balance_alter_balance_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=255, unique=True)),
                ('network_url', models.CharField(max_length=255)),
                ('network_ABI', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.network'),
        ),
    ]
