# Generated by Django 5.0.3 on 2024-03-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_network_balance_network_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='network_name',
            new_name='network',
        ),
        migrations.AlterField(
            model_name='network',
            name='network_ABI',
            field=models.CharField(max_length=25500),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_url',
            field=models.URLField(max_length=255),
        ),
    ]
