# Generated by Django 5.0.3 on 2024-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_remove_balance_network_alter_network_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_sum',
            field=models.IntegerField(default=0),
        ),
    ]
