# Generated by Django 5.0.3 on 2024-04-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_wallet_wallet_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='network_chain',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_ABI',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_sum',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(default='')),
                ('asset_address', models.CharField(blank=True, max_length=255)),
                ('balance', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('track', models.BooleanField(default=False)),
                ('delta', models.FloatField(default=0.01)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('network_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.network')),
                ('wallet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.wallet')),
            ],
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
