name: traefik

on: 
  push:
    branches: [main]

jobs: 
  traefik: 
    runs-on: self-hosted
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2   
      - name: Deploy to prod
        run: |
          docker network create --driver=bridge --attachable --internal=false web
          cd traefik && docker-compose -f  ./docker-compose.yml up -d
